# Generated by Django 5.2.8 on 2025-11-28 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.grades'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='school.subject'),
        ),
    ]
